//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace integrationWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderAero
    {
        public int id { get; set; }
        public Nullable<int> idCustomer { get; set; }
        public Nullable<int> idRoute { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Route Route { get; set; }
    }
}
