//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace integrationWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Route
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Route()
        {
            this.OrderAero = new HashSet<OrderAero>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> sending_point { get; set; }
        public Nullable<int> destination { get; set; }
        public Nullable<int> cost { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public Nullable<System.DateTime> return_date { get; set; }
        public Nullable<int> @class { get; set; }
        public Nullable<System.TimeSpan> start_time { get; set; }
        public Nullable<System.TimeSpan> end_time { get; set; }
    
        public virtual cities cities { get; set; }
        public virtual cities cities1 { get; set; }
        public virtual @class class1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderAero> OrderAero { get; set; }
    }
}
